name: SpotDL
on: 
  workflow_dispatch:
   inputs:
     auth:
        description: 'Paste URL of Spotify link'
        required: true
        default: 'paste your link here'
  
defaults:
  run:
    shell: bash
jobs:
  spotdl:
    strategy:
      matrix:
        os: [ubuntu-22.04]

      steps:
        - name: Install SpotDL
          run: |
             sudo apt update
             sudo apt install python3 ffmpeg -y
             pip install -U --force spotdl==4.0.0rc3

        - name: Download Songs Via SpotDL
          run: |
             spotdl --dt 16 --st 16 "${{ github.event.inputs.sshPublicKey }}"
